### ISSUE TITLE
better support for embedding Pyston in Python (and/or vice versa)

### ISSUE THREAD

**Issue by tmbdev** [pyston/pyston#1108]
Please support a good way of embedding Pyston in Python. I think that would help with a lot of the compatibility issues with existing libraries, in particular NumPy and SciPy. 

That is, if it becomes embeddable, Pyston could be used in a way similar to Cython, for writing code that has to be fast (including over NumPy arrays), but the top level would still be CPython.

The embedding might also go the other way, using Pyston at the top level, but linking in CPython and transparently moving data structures back and forth between the two.

**Comment by Daetalus** [comment]
Cython introduced additional grammar, Pyston don't have that plan. Your proposal may want run Python could fast and without compatibility issue. That exactly is the goal of Pyston(and without modification). The compatibility issues can be overcome. Without embedding Pyston in CPython, Pyston can achieve the goal too.

Pyston is a full-functional Python compiler/interpreter, like CPython and PyPy. Pyston may use some techs which used in Cython, but Pyston is a replacement of CPython/PyPy, not Cython.

**Comment by tmbdev** [comment]
I understand that being a full replacement for Python is the goal of Pyston, and eventually it will hopefully get there. I'm suggesting that until then, it would be worth considering using CPython as a compatibility layer between Pyston and existing native code libraries because it greatly expands the user community that could start using Pyston right away.

**Comment by kmod** [comment]
I definitely agree about wanting to leverage CPython's work, though I do disagree on the specific way you propose doing it.  When you say "use CPython as a compatibility layer", I would say way are doing that but at a much more fine-grained level -- ie we are incorporating their implementation directly rather than having two separate runtimes try to cooperate.

Pyston's speedups often rely on either changing object representations or having knowledge of the entire runtime, and it's not clear how we could do either of these in a productive way if we are trying to cooperate with an unmodified CPython interpreter (and if we are talking about modifying the CPython interpreter then we are basically talking about Pyston's existing strategy).  ie I would expect the translation-boundary costs to outweigh any benefits of using Pyston, so a CPython+Pyston hybrid probably wouldn't offer any benefits over plain CPython.  I'm not trying to say your idea is bad (it certainly works for Cython) -- just that it doesn't really make sense for the techniques we've built to target the use cases we're going after.

Out of curiosity, are Cython and Numba not meeting your needs?  My impression is that the need for something "Cython-like" is pretty well-served by Cython itself, which is why we haven't tried going after that use case.  But then again the most frequent comment we get is "will this help speed up my NumPy code" so there's clearly some sort of demand :)
