### ISSUE TITLE
Different between call slot directly and call cls->xxx

### ISSUE THREAD

**Issue by Daetalus** [pyston/pyston#1180]
In CPython, slot was called by something like `xxx->tp_as_number->nb_hex`. However, in Pyston, slot was called by `cls->__hex__`. Does it has incompatility between CPython and Pyston?

**Comment by kmod** [comment]
As much as I want to be "bug for bug" compatible with CPython, when it comes to the C API I think that there might just be too many kinds of bugs that extensions could have.  Extensions have direct control over the memory so there has to be some point that we can't really stop their issues from causing trouble :/

In this case though I think we might be able to fix it somewhat easily and also get better performance -- instead of just calling `__hex__`, we should do what we do in some other places, which is something like `if (nb_hex != slot_nb_hex) return nb_hex(); else return __hex__()`.  The reasoning is that if `__hex__` is set to a python function, calling it will be much faster than calling `nb_hex` which will end up just proxying through slot_nb_hex, which the JIT can't understand. 

Actually in the case of `hex`, there's no rewriter support anyway, so we could just change it to calling nb_hex.

**Comment by Daetalus** [comment]
What is the performance difference between those two implementation?

**Comment by kmod** [comment]
There are a few cases:
- Function defined in Python, JIT is off: they are the same speed
- Python function, JIT is on: calling the Python version is much better
- C function, JIT is off: calling the C slot is much, much better
- C function, JIT is on: they are roughly the same speed

So if we are already limiting ourselves to the "JIT is off" case, we should just call the C slot.  We can get wins by calling the Python version at the right times, but that also requires adding JIT support.
