### ISSUE TITLE
Pyston generatorSendInternal triggered an assert when run Cython tests.

### ISSUE THREAD

**Issue by Daetalus** [pyston/pyston#1240]
When run Cython tests(`python runtests.py` in Pyston virtualenv). It will encounter this assert.

```
==============================
python: ../../src/runtime/generator.cpp:158: bool pyston::generatorSendInternal(pyston::BoxedGenerator *, pyston::Box *) [S = pyston::ExceptionStyle::CAPI]: Assertion `!self->returnValue' failed.
```

Sorry, I can't give more information about it. Just file an issue as a reminder.

**Important:** 
In order to run Cython test, you need to do some workarounds:
- Comment out this line: https://github.com/dropbox/pyston/blob/master/src/runtime/code.cpp#L140
- Enable this line and comment out the two lines below: https://github.com/dropbox/pyston/blob/master/from_cpython/Include/boolobject.h#L13

**Notes:** The test need run nearly 1 hour on my laptop(i7-4700HQ CPU).

**Comment by kmod** [comment]
Awesome, sounds like this is finding some good stuff :)

When you are ready, it might be nice to commit your testing strategy as an integration test.  You can even do that now if you want and mark it `skip-if: True` so that it doesn't get run, but it can still serve as a way of documenting+sharing how you're testing things.
