### ISSUE TITLE
Cannot compile uWSGI on pyston/pyston Docker machine

### ISSUE THREAD

**Issue by alanjds** [pyston/pyston#1264]
I got a generic `AttributeError: 'NoneType' object has no attribute 'split'` when trying to build under the docker image.

Some more details and discussion occurred on Gitter: https://gitter.im/dropbox/pyston?at=576b0221c7594b5f0dd1da74

Not sure if patches shoud land on uWSGI or Pyston, but they are incompatible right now.

(cross-posted with https://github.com/unbit/uwsgi/issues/1302)

**Comment by tangwz** [comment]
I hava some question when I used `pip install uwsgi`.

**Comment by kmod** [comment]
Just posting in some of the chat logs from earlier.  This was annoying to debug because they do `exec(f.read(), up)`, which doesn't give a meaningful stack trace.  I changed it to execfile and got this:
```
  File "uwsgiconfig.py", line 1605, in <module>
    build_uwsgi(uc, is_cflags, gcll=gcll)
  File "uwsgiconfig.py", line 458, in build_uwsgi
    execfile('%s/uwsgiplugin.py' % path, up)
  File "plugins/python/uwsgiplugin.py", line 20, in <module>
    LIBS = sysconfig.get_config_var('LIBS').split() + sysconfig.get_config_var('SYSLIBS').split()
AttributeError: 'NoneType' object has no attribute 'split'
```

This particular issue is pretty easy to address, but after I fixed it I ran into several more difficult uwsgi issues.
