### ISSUE TITLE
Transfer Pyston repo to an open-source account

### ISSUE THREAD

**Issue by kmod** [pyston/pyston#1422]
Hi @lfaraone, can we transfer this repository to the @pyston account?  This way we could keep working on it without keeping the acls tied to the Dropbox org.  We're also happy to submit acl-change requests to you guys if you prefer.  (In which case, can we give @undingen write access?)

Transferring seems like a better option than forking, so that we can keep issues, pull requests, etc.  And stars, we want to keep the stars.

**Comment by lfaraone** [comment]
@kmod: I'll get back to you on that — I think the latter is definitely not a problem. 

@undingen already has write access, though?

**Comment by leycec** [comment]
If transferring this repository to @pyston is infeasible, <sup>because... *capitalism*</sup> a fork would be dramatically preferable for the long-term safety of this project. Non-proprietary, community ownership is key.

In that case, existing issues and pull requests would continue to reside here – permanently unresolved (*which is bad*), at least trivially cross-referencable from the fork (*which is less bad*), and possibly migratable into the fork with existing automation like [this](https://github.com/google/github-issue-mover) or [this](https://github.com/IQAndreas/github-issues-import) (*which is great if actually working*). Stars would, of course, be lost. All three are ultimately a small price to pay for genuine ownership.

**Comment by Daetalus** [comment]
Hello, what kind of problems blocking the transferring? I mean transfer this repository to the @pyston account? Thanks!

**Comment by kmod** [comment]
Hey @lfaraone, any word on this?  I'm happy to do what I can to help make this happen; feel free to put me in touch with other people who I might need to talk to.
