### ISSUE TITLE
Range should support long

### ISSUE THREAD

**Issue by ghost** [pyston/pyston#256]
Hi, this is just a note that the `range` function should support `long` type arguments according to CPython.

**Comment by corona10** [comment]
In my cpython 2.7.8

if i call ' a = range(122978293824730344101229782938247303441) ' 
it occurred error message 'OverflowError: range() result has too many items'

**Comment by corona10** [comment]
In my cpython 2.7.8

if i call ' a = range(122978293824730344101229782938247303441) ' 
it occurred error message 'OverflowError: range() result has too many items'

**Comment by tjhance** [comment]
That's true, but `range` needs to support `long` arguments regardless. For example,

```python
>>> range(122978293824730344101229782938247303441, 122978293824730344101229782938247303443)
[122978293824730344101229782938247303441L, 122978293824730344101229782938247303442L]
```

**Comment by corona10** [comment]
now pyston support long argument such as '3L' but it did not support yet large number such as '122978293824730344101229782938247303441' it need more fixing

**Comment by kmod** [comment]
For this kind of thing, I think it's better to just look at the CPython implementation rather than try to reverse engineer it.  The relevant functions here are `builtin_range` and `handle_range_longs` -- looks like CPython will allow ranges of non-int-size values if the size of the range is less than INT_MAX or some such.
