### ISSUE TITLE
Generate smaller patchpoints

### ISSUE THREAD

**Issue by undingen** [pyston/pyston#264]
Our patchpoint's are currently very large and and memory inefficient:

``` asm
     a5a:       48 b8 08 f0 00 70 12    movabs $0x127000f008,%rax
     a61:       00 00 00 
     a64:       48 3b 07                cmp    (%rdi),%rax
     a67:       0f 85 ec 01 00 00       jne    0xc59
     a6d:       48 b8 08 f0 00 70 12    movabs $0x127000f008,%rax
     a74:       00 00 00 
     a77:       48 3b 06                cmp    (%rsi),%rax
     a7a:       0f 85 d9 01 00 00       jne    0xc59
     a80:       48 b8 08 f0 00 70 12    movabs $0x127000f008,%rax
     a87:       00 00 00 
     a8a:       48 3b 06                cmp    (%rsi),%rax
     a8d:       0f 85 c6 01 00 00       jne    0xc59
     a93:       48 8b 07                mov    (%rdi),%rax
     a96:       48 b9 08 c4 00 70 12    movabs $0x127000c408,%rcx
     a9d:       00 00 00 
     aa0:       48 3b 08                cmp    (%rax),%rcx
     aa3:       0f 85 b0 01 00 00       jne    0xc59
     aa9:       48 b9 88 33 00 70 12    movabs $0x1270003388,%rcx
     ab0:       00 00 00 
     ab3:       48 3b 88 80 01 00 00    cmp    0x180(%rax),%rcx
     aba:       0f 85 99 01 00 00       jne    0xc59
     ac0:       48 8b 80 88 01 00 00    mov    0x188(%rax),%rax
     ac7:       48 8b 80 80 00 00 00    mov    0x80(%rax),%rax
     ace:       48 b9 08 f4 00 70 12    movabs $0x127000f408,%rcx
     ad5:       00 00 00 
     ad8:       48 3b 08                cmp    (%rax),%rcx
     adb:       0f 85 78 01 00 00       jne    0xc59
     ae1:       48 b9 e8 1a 02 70 12    movabs $0x1270021ae8,%rcx
     ae8:       00 00 00 
     aeb:       48 39 c1                cmp    %rax,%rcx
     aee:       0f 85 65 01 00 00       jne    0xc59
     af4:       49 bb 90 aa 6b 00 00    movabs $0x6baa90,%r11
     afb:       00 00 00 
     afe:       41 ff d3                callq  *%r11
     b01:       e9 b2 07 00 00          jmpq   0x12b8

```

Loading the addresses of a GC allocated address takes 10 bytes on x86_64 because the immediate does not fit in 32bits.  
One way to make them smaller would be to teach our rewriter to reuse an register if it stores already the needed value. For large immediate values which have a similar value to another one we could load the immediate with a `lea` and difference between the two immediate values. In addition we may want to remove duplicate guards.

**Comment by kmod** [comment]
+1, we can definitely do way better here.

It looks like we could hack the large-constant-optimization into the current system without too much trouble (separate out a getLargeConstant() function which looks for existing constants in registers, and makes sure to save the constant it generates in the vars array [which is the hacky part since it's happening in the wrong rewriter phase]).  Maybe we could eliminate duplicate guards in particular by storing, per RewriterVar, which offsets+expected_val we've guarded on?

I wonder if it makes sense to do something more complicated for rewrites, such as having some sort of IR and doing simple optimizations on it -- in theory, we could even use LLVM for rewrites.
