### ISSUE TITLE
can't run tests if pyston is broken

### ISSUE THREAD

**Issue by tjhance** [pyston/pyston#616]
One part of the build system is self-hosted (by necessity, apparently)

```
ninja -C /home/tjhance/pyston/build/Debug pyston copy_stdlib copy_libpyston sharedmods ext_pyston ext_cpython 
ninja: Entering directory `/home/tjhance/pyston/build/Debug'
[4/4] Generating basic_test.pyston.so
FAILED: cd /home/tjhance/pyston/test/test_extension && /home/tjhance/pyston/build/Debug/pyston setup.py build --build-lib /home/tjhance/pyston/build/Debug/test/test_extension
Segmentation fault (core dumped)
[4/4] Generating ../lib_pyston/_multiprocessing.pyston.so, ../lib_pyston/pyexpat.pyston.so, ../lib_pyston/_elementtree.pyston.so
FAILED: cd /home/tjhance/pyston/from_cpython && /home/tjhance/pyston/build/Debug/pyston setup.py build --build-lib /home/tjhance/pyston/build/Debug/lib_pyston
Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.
make: *** [pyston_dbg] Error 1
```

This means that if pyston is broken, `make check` and related tools can't even get to the point where they run tests. And then you can't debug pyston!

Most tests don't actually need these extension modules, so we should delay building them until after most tests have run.

**Comment by kmod** [comment]
One idea would be to not rebuild extension modules when we rebuild pyston.  ie as long as you build once with a good revision, you should be able to go to a bad revision and not hit this behavior.  I don't think it would hurt anything, but it opens up to the even-harder-to-diagnose case where the extension module has a bug because the pyston that built it had a bug, and it doesn't go away even if you fix the underlying pyston bug.  I think the chances of that are rare, so maybe it's worth trying out?

@dagar is there a good way we could create that behavior in the build system?  We want to make sure that the extension modules exist, but if they already exist to not recreate them (except if the includes change).  I think I had this behavior accidentally when I made [sharedmods](https://github.com/dropbox/pyston/blob/master/from_cpython/CMakeLists.txt#L136) depend on `pyston`, rather than the current way we do it of having the .so files depend on `pyston`, but I'm not sure if that's a good approach.

**Comment by dagar** [comment]
CPython has the same problem. Two simpler options that come to mind.
 * add a simple test target that builds pyston_debug with minimal dependencies and runs some basic testing to be used in these situations. eg `make check_sanity`
 * option to easily switch (or fallback with a warning?) to cpython instead of pyston self hosting

**Comment by tjhance** [comment]
Another option is to disable complex features (like the JIT) for this step.

**Comment by kmod** [comment]
I think figuring out why the bootstrap failed is only part of the problem; I often do things for debugging that purposefully don't end up in a working pyston binary, which I want to use for testing.  And I don't think cpython can do this part of the build for us without some heavy hacking; ie it's not just this situation, but also we can't build extensions for cpython to run, and cpython can't build extensions for different versions of cpython to run.  We could probably make this work if we really wanted to (would need to get cpython to use our modified distutils, would need to figure out how to tell distutils to use a different set of configuration data), but I guess my point is that it's not just a matter of using a different python implementation.

So I guess the only options I can think of are to not rebuild the extension modules, or to convert that part of the build back away from distutils.  Our current setup.py is very simple so it would be pretty easy to just have CMake handle it (we used to do this), though the counter-argument is that we'll want to eventually use more of CPython's 2kloc setup.py.  Anyway, I think it'll just be a matter of waiting for someone to be sufficiently frustrated/motivated to switch it back to cmake :)

**Comment by dagar** [comment]
How about this? PR #620 

 * build just pyston
 * run test/tests (with all extension related tests removed)
 * build and test everything else (extensions, etc)

**Comment by kmod** [comment]
I think that would help specifically with the case of running the tests, but your next step will usually be to run the debugging helpers.  Or maybe I'm the only one who uses those...  but anyway I think it'd be nice to find a solution that helped with more development workflows.

**Comment by dagar** [comment]
Oh right, you don't symlink the binary until the entire build succeeds. How about the pyston_{dbg, release} targets build pyston, symlink, then build the rest.

Added to PR #620

**Comment by tjhance** [comment]
If by "debugging helpers" you mean `make dbg_testname`, I use those frequently too.

**Comment by dagar** [comment]
Alright, I think I actually understand your problem now. I'm probably the only person using cmake directly (skipping Makefile). I'll see what I can come up with.
