### ISSUE TITLE
Release for OS X?

### ISSUE THREAD

**Issue by TofPlay** [pyston/pyston#998]
Do you have a release for OS X?

**Comment by undingen** [comment]
Unfortunately no, at the moment pyston only run on x86-64 linux :-(

**Comment by auvipy** [comment]
what should be done to have a python 3.5/3.6 version of pytson for ubuntu 64 bit plateform

**Comment by undingen** [comment]
At the moment we only support python 2.7 and have currently no time to add python 3 support :-(. (see FAQ: https://github.com/dropbox/pyston/wiki/FAQ).

**Comment by auvipy** [comment]
I want to work on python3 support and for that atleast want to give a dive. plz show some path

**Comment by kmod** [comment]
Unfortunately supporting Python 3 would probably mean creating a new branch in our codebase and then adding Python 3 support there.  We're more than happy to help if you're interested in trying this out, but just so you know we won't have time to help maintain this alternate branch so I think it would quickly go out of date.

My guess is that Python 3 support will have to wait until Dropbox starts wanting to switch to Python 3 internally.

**Comment by auvipy** [comment]
there are two option for me, fork the master and try to understand the 2.7 versions mechanism, and create a new branch on my fork to investigate/figure out how to keep both versions working on a single base, though I know that will be really tough. I use python 2.7 and 3.4/3.5 both on by regular projects. My intentions are learning through experiment. [I use ubuntu linux 14.04 lts 64bit]

**Comment by Daetalus** [comment]
I want to let Pyston support Python 3 too, but after some investigation, I think it's better to wait until Pyston Python 2 become more mature.

There have several reasons:

- The libpypa only support Python 2 syntax for now. And it still contains some bugs(e.g. the complex parsing). If want to support Python 3. We need to let libpypa support Python 3 first.
- Some Pyston fundamental components still evolving. I think it is harder to merge changes from Pyston official branch to Pyston Python 3 branch(let's say Pyston 3) instead fork a branch when Pyston 2 get ready in future. (unless the number of contributors are same in Pyston 3 and Pyston 2. Otherwise either the Pyston 2 would quickly go out of date, or most of time you are dealing with the conflict between Pyston official branch and Pyston 3 branch.)
- Pyston 2 runtime still missing some features and contains bugs. If fork a branch based on it. I'm afraid that the main task is still to improve the runtime rather than support Python 3 features.

Improve the current Pyston runtime(by fix the bugs in CPython tests) is a good start I think.

**Comment by auvipy** [comment]
@Daetalus can't disagree  and convinced with your insights.

**Comment by Daetalus** [comment]
@auvipy That's OK. :smile:

**Comment by undingen** [comment]
Concerning the parser I think it's better to try to merge cpythons 3.x parser support into the 2.x we already use in REPL mode instead of extending pypa....
